export TEST_BASE=/home/hank.fisher/MET9_0_1_nopython
export COMPILER=gnu
export MET_SUBDIR=/home/hank.fisher/MET9_0_1_nopython
export MET_TARBALL=met-9.0.1.20200423.tar.gz
#export MET_PYTHON_CC=-I/usr/include/python2.7
#export MET_PYTHON_LD="-L/usr/lib/python2.7 -lpthread -ldl -lutil -lm -lpython2.7 -Xlinker -export-dynamic"
#export MET_PYTHON_LD="-L/usr/lib/python2.6 -lpthread -ldl -lutil -lm -lpython2.6"
#export MET_PYTHON_CC=-I/usr/include/python3.6m
#export MET_PYTHON_LD="-L/usr/lib64 -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic"
#export MET_PYTHON_LD="-L/usr/local/lib/python3.6 -lpthread -ldl -lutil -lm -lpython3.6 -Xlinker -export-dynamic"
#export MET_GRIB2CLIB=/home/hanke.fisher/MET9_0_1_nopython/external_libs
#export MET_BUFRLIB=/home/hanke.fisher/MET9_0_1_nopython/external_libs
#export MET_NETCDFLIB=/home/hanke.fisher/MET9_0_1_nopython/external_libs
export LD_LIBRARY_PATH=/home/hank.fisher/MET/external_libs/lib
export OPT_ARGS="-L/home/hank.fisher/MET/external_libs/lib"
export CPPFLAGS="-I/home/hank.fisher/MET/external_libs/include"
export LDFLAGS=-"Wl,-rpath,/home/hank.fisher/MET/external_libs/lib"
export PYTHON_MODULE_USE=0
export USE_MODULES=FALSE
